### ISSUE TITLE
Problems encountered during the training and testing phase

### ISSUE THREAD

**Issue by zhuwenya0000** [RealZST/TD3-based_UAV_Collision_Avoidance#1]
Excuse me, I used the TD3 algorithm for training with seed=8 and max_episodes=5000, but encountered the following problem,

1. The success rate during the training phase is 0, and the drone reaches the vicinity of the target without terminating the training.
![91d46488b661a9d754588b758dce9b5](https://github.com/RealZST/TD3-based_UAV_Collision_Avoidance/assets/143677777/11939898-9c1c-4814-858a-7d5c03e9932e)

2.During the testing phase, the drone reaches the vicinity of the target point, the training does not terminate, and it flies around the target point.
![c70f9d04804fe0125042395f45887ed](https://github.com/RealZST/TD3-based_UAV_Collision_Avoidance/assets/143677777/e9da026c-fae2-4b0b-91f7-9e09e59aad5d)
May I ask where I went wrong? What modifications do I need? Looking forward to your response.

**Comment by RealZST** [comment]
To make the drone approach the target in the direction toward the target, the reward function contains the negative value of the angle between the drone's first-person perspective direction and the line connecting the drone to the target.

When the drone is near the target, even a slight change in the drone's direction can result in a significant change in the mentioned angle, leading to a penalty in the reward function's angle part.

Therefore, the drone may fly around the target as it is finding an action that reduces the angle penalty.

You could solve the issue by simply expanding the target area or refining the angle part of the reward function.

**Comment by zhuwenya0000** [comment]
> 为了使无人机朝向目标的方向接近目标，奖励函数包含无人机的第一人称视角方向与连接无人机与目标的线之间夹角的负值。
> 
> 当无人机靠近目标时，即使无人机方向的轻微变化也会导致上述角度发生重大变化，从而导致奖励函数的角度部分受到惩罚。
> 
> 因此，无人机可能会绕着目标飞行，因为它正在寻找减少角度惩罚的动作。
> 
> 您可以通过简单地扩展目标区域或优化奖励函数的角度部分来解决这个问题。
Thank you for your reply
