### ISSUE TITLE
 cannot import name 'UnityEnv' from 'gym_unity.envs'

### ISSUE THREAD

**Issue by The-never-lemon** [RealZST/TD3-based_UAV_Collision_Avoidance#2]
![屏幕截图 2024-04-01 170628](https://github.com/RealZST/TD3-based_UAV_Collision_Avoidance/assets/86717385/ee9d785c-f459-4cfb-8a21-5af94bd7992e)
您好，我在测试您的代码的时候遇到了这个问题，请问是缺少了某个库没有安装吗？

**Comment by RealZST** [comment]
Yes. Please install the gym wrapper using:

```sh
pip install gym_unity
```

**Comment by The-never-lemon** [comment]
> Yes. Please install the gym wrapper using:
> 
> ```shell
> pip install gym_unity
> ```

I have already install the package ,I still have this problem.  :(
![屏幕截图 2024-04-01 220515](https://github.com/RealZST/TD3-based_UAV_Collision_Avoidance/assets/86717385/47ea300f-44ef-46fe-a617-c36fb07ba91b)

**Comment by RealZST** [comment]
The version 0.28.0 is not compatible because UnityEnv has been deprecated in the latest release. Please refer to the [dependencies](https://github.com/RealZST/TD3-based_UAV_Collision_Avoidance?tab=readme-ov-file#dependencies) in readme.

> ml-agents 0.15.1

https://github.com/Unity-Technologies/ml-agents/tree/0.15.1/gym-unity

**Comment by The-never-lemon** [comment]
> The version 0.28.0 is not compatible because UnityEnv has been deprecated in the latest release. Please refer to the [dependencies](https://github.com/RealZST/TD3-based_UAV_Collision_Avoidance?tab=readme-ov-file#dependencies) in readme.
> 
> > ml-agents 0.15.1
> 
> https://github.com/Unity-Technologies/ml-agents/tree/0.15.1/gym-unity

Thank you for your reply. ：）I will try it later
