### ISSUE TITLE
when I was training the model, it stopped at some episode 

### ISSUE THREAD

**Issue by The-never-lemon** [RealZST/TD3-based_UAV_Collision_Avoidance#3]
when I was training the model, it stopped at some episode without moving on. The drone was flying around the corner. Can you tell me how I can modify it?

**Comment by RealZST** [comment]
It's normal to have the mentioned situation during the training. After about 500 episodes, as the policy updates, the UAV should begin to fly towards the target point. You could speed up the training process by adjusting the time scale setting in Unity (typically, can be set up to a maximum of 100), which controls how fast time passes within the simulation.
